FROM centos:latest
LABEL description="LHCbPR2 ROOT Service"
###############################################################################
RUN yum -y install \
	bzip2 \
	epel-release \
	gcc-c++ \
	git \
	libjpeg \
	libpng
	# python-devel \
	# python-gunicorn

RUN yum -y install python-pip
RUN yum -y clean all
###############################################################################
ENV WWW /opt/www
ENV ROOT_DATA /opt/data
ENV PREFIX /opt
ENV ROOTSYS $PREFIX/root

ENV FLASK_PORT 80
ENV FLASK_HOST 0.0.0.0
###############################################################################
# add custom ssh config / keys to the root user
ADD .ssh/ /root/.ssh/
# Fixes permission if needed
RUN chmod 600 /root/.ssh/*

###############################################################################
ADD https://root.cern.ch/download/root_v6.06.00.Linux-centos7-x86_64-gcc4.8.tar.gz /var/tmp/root.tar.gz
RUN tar xzf /var/tmp/root.tar.gz -C $PREFIX && rm /var/tmp/root.tar.gz
###############################################################################
RUN mkdir $WWW $ROOT_DATA
# RUN groupadd -r www -g 1000 && useradd -u 1000 -r -g www -m -d $WWW -s /sbin/nologin -c "www user" www && \
#     chmod 755 $WWW

WORKDIR $WWW
###############################################################################§
RUN git clone ssh://git@gitlab.cern.ch:7999/lhcb-core/LHCbPR2ROOT.git .
RUN pip install -r requirements.txt
RUN cp -r data/* $ROOT_DATA/
###############################################################################
VOLUME $ROOT_DATA
EXPOSE $FLASK_PORT
###############################################################################
CMD ["./scripts/bootstrap"]
