FROM mazurov/cern-root:latest
LABEL description="ROOT json service"

ENV CODE /code
ENV ROOT_DATA /data

ENV FLASK_PORT 8080
ENV FLASK_HOST 0.0.0.0

RUN mkdir $ROOT_DATA
ADD . $CODE
WORKDIR $CODE

RUN pip install -r requirements.txt
COPY data/* $ROOT_DATA/

VOLUME $ROOT_DATA
VOLUME $CODE

EXPOSE $FLASK_PORT
CMD ["./scripts/bootstrap"]
